/** Declaration file generated by dts-gen */

export function decode(buf: any, options: any, cb: any): void;

export function encode(buf: any, options: any, cb: any): any;

export function exif(buf: any, options: any, cb: any): void;

export function info(buf: any, cb: any): void;

export function magic(buf: any, cb: any): void;

export namespace decode {
    const prototype: {
    };

}

export namespace encode {
    const prototype: {
    };

}

export namespace exif {
    const prototype: {
    };

}

export namespace info {
    const prototype: {
    };

}

export namespace magic {
    const prototype: {
    };

}

